accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    # urls from post app
    url(r'^posts/', include('posts.urls')),
    url(r'^bio/$', views.bio),
    url(r'^$', views.home)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.posts_list, name='list'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100] + "..."

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()
            login(request, user)
            return redirect('posts:list')
            # sending to the posts list
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    #return HttpResponse('homepage')
    return render(request,'home.html')

def bio(request):
    #return HttpResponse ('bio')
    return render(request, 'bio.html')

posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse
from .models import Post

def posts_list(request):
    posts = Post.objects.all().order_by('date')
    return render(request, 'posts/posts_list.html', {'posts': posts})


def post_detail(request, slug):
    #return HttpResponse(request, slug)
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/posts_detail.html', {'post': post})

accounts/templates/accounts/login.html
{% extends 'layout.html'%}


{% block content%}

<h1>Log in</h1>
<form class="site-form" action="/accounts/login/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'layout.html'%}


{% block content%}

<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>

{% endblock %}

posts/templates/posts/posts_detail.html
{% extends 'layout.html'%}

{% block content %}
<div class="post-detail">
    <div class="post">
        <h2>{{post.title}}</h2>
        <p>{{post.date}}</p>
        <img src="{{post.thumb.url}}"/>
        <p>{{post.body}}</p>
        <p>{{post.body}}</p>
    </div>
</div>

{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block content %}
    <h1>My posts</h1>
    <div class="posts">
        {% for post in posts %}
        <div class="post">
            <h2><a href="{% url 'posts:detail' slug=post.slug %}">{{post.title}}</a> </h2>
            <p>{{post.date}}</p>
            <p>{{post.snippet}}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/bio.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Bio
    </title>
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
    <h1>Paul</h1>
    <p> Psychologist & programming enthusiast</p>

</body>
</html>

templates/home.html
{% load static from staticfiles %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            Welcome
        </title>
        <link rel="stylesheet" href="{% static 'style.css'%}">
    </head>
    <body>
    <h1> Welcome to the Paul's blog </h1>
    <p> This is one of my new Django project</p>
    </body>
</html>

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header class="wrapper">
        <h1><a href="{% url 'posts:list' %}">Posts</a></h1>
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {%csrf_token%}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>